name: Publish Gem
on:
  push:
    branches:
      - "*"
    tags:
      - v*
jobs:
  deploy:
    concurrency:
      group: deploy
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: fregante/setup-git-user@v2

      - name: Bump gem version
        run: |
          gem install bump
          bump patch --changelog

      - name: Build gem and release to Rubygems
        uses: cadwallion/publish-rubygems-action@master
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push code to main
        run: git push origin -f main

      - name: Get current gem version
        run: echo "::set-output name=version::$(bin/bump current)"
        id: gem

      - name: Create github release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ steps.gem.outputs.version }}
          tag_name: v${{ steps.gem.outputs.version }}
          prerelease: false
          draft: false

      - name: Publish gem to Github
        uses: jstastny/publish-gem-to-github@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: oleander
